language: python
matrix:
 include:
  - python: 2.7
    env:
     - TOX_ENV=py27
  - python: 3.4
    env:
     - TOX_ENV=py34
  - python: 3.5
    env:
     - TOX_ENV=py35
  - python: 3.6
    env:
     - TOX_ENV=py36
  - python: 3.7
    dist: xenial
    sudo: yes
    env:
     - TOX_ENV=py37
  - python: 3.6
    env:
     - TOX_ENV=check-format
  - python: 3.6
    env:
     - TOX_ENV=flake8
  - python: 3.6
    env:
     - TOX_ENV=bandit
  - python: 3.6
    env:
     - TOX_ENV=safety
  - python: 3.6
    env:
     - TOX_ENV=coverage
install:
 - pip install tox
script:
 - tox -e $TOX_ENV
