language: python
python: 3.6
env:
 - TOX_ENV=py27
 - TOX_ENV=py34
 - TOX_ENV=py35
 - TOX_ENV=py36
 - TOX_ENV=py37
 - TOX_ENV=pypy
 - TOX_ENV=check-format
 - TOX_ENV=flake8
 - TOX_ENV=bandit
 - TOX_ENV=safety
 - TOX_ENV=coverage
install:
 - pip install tox
script:
 - tox -e $TOX_ENV
