language: python
matrix:
 include:
  - python: 3.4
    env:
     - TOX_ENV=py34
  - python: 3.7
    dist: xenial
    sudo: yes
    env:
     - TOX_ENV=py37
  - os: osx
    language: generic
    python: 3.6
    env:
      - TOX_ENV=py36
  - os: windows
    language: sh
    python: 3.7
    before_install:
      - choco install python3
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      - python -m pip install --upgrade pip wheel
    env:
     - TOX_ENV=py37
  - python: 3.5
    env:
     - TOX_ENV=py35
  - python: 3.6
    env:
     - TOX_ENV=py36
  - python: 3.6
    env:
      - TOX_ENV=pypy3.6
  - python: 3.6
    env:
     - TOX_ENV=check-format
  - python: 3.6
    env:
     - TOX_ENV=flake8
  - python: 3.6
    env:
     - TOX_ENV=bandit
  - python: 3.6
    env:
     - TOX_ENV=safety
  - python: 3.6
    env:
     - TOX_ENV=coverage
install:
 - pip install --upgrade tox
script:
 - tox -e $TOX_ENV
